
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"

x-labels:
  &default-labels
  logging: "promtail"
  logging_jobname: "containerlogs"

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: api-gateway
    environment:
      - SERVICE_NAME=api-gateway
    ports:
      - 5000:5000
    depends_on:
      - order-service
      - inventory-service
      - payment-service
      - warehouse-service
      - fraud-service
    networks:
      - traces
    labels: *default-labels
    logging: *default-logging

  order-service:
    container_name: order-service
    build:
      context: order
    environment:
      - SERVICE_NAME=order-service
    depends_on:
      - inventory-service
    networks:
      - traces
    labels: *default-labels
    logging: *default-logging

  inventory-service:
    container_name: inventory-service
    build:
      context: inventory
    environment:
      - SERVICE_NAME=inventory-service
      - INVENTORY_AVAILABILITY=1000
    depends_on:
      - warehouse-service
    networks:
      - traces
    labels: *default-labels
    logging: *default-logging

  warehouse-service:
    container_name: warehouse-service
    build:
      context: warehouse
    environment:
      - SERVICE_NAME=warehouse-service
      - INVENTORY_AVAILABILITY=1000
    networks:
      - traces
    labels: *default-labels
    logging: *default-logging

  payment-service:
    container_name: payment-service
    build:
      context: payment
    environment:
      - SERVICE_NAME=payment-service
      - FRAUD_SERVICE_URL=http://fraud-service:5000
    depends_on:
      - fraud-service
    networks:
      - traces
    labels: *default-labels
    logging: *default-logging

  fraud-service:
    container_name: fraud-service
    build:
      context: fraud
    environment:
      - SERVICE_NAME=fraud-service
      - FRAUD_PERCENTAGE=5
      - NOT_FRAUD_PERCENTAGE=95
    networks:
      - traces
    labels: *default-labels
    logging: *default-logging

 

networks:
  traces:
    name: traces
    driver: bridge
